# # こちらは手動実行で、環境を作成

name: manual exection customer specific update
run-name: all update customer specific infra run by ${{ github.actor }}

on: workflow_dispatch

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  manual-approval:
    environment: manual-approval
    runs-on: ubuntu-24.04
    steps:
      - name: manual approval
        shell: bash
        run: echo "approval."

  all_update_customer_specific_infra_plan:
    needs: manual-approval
    strategy:
      matrix:
        customers:
          [
            "develop-customer-specific-fixer",
            "develop-customer-specific-hoge",
            "develop-customer-specific-piyo",
          ]
    uses: ./.github/workflows/update-infra-plan.yaml
    with:
      environment: ${{ matrix.customers }}
    secrets:
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS_DEVELOPMENT }}

  all_update_customer_specific_infra_apply:
    needs: all_update_customer_specific_infra_plan
    strategy:
      matrix:
        customers:
          [
            "develop-customer-specific-fixer-required-approval",
            "develop-customer-specific-hoge-required-approval",
            "develop-customer-specific-piyo-required-approval",
          ]
    uses: ./.github/workflows/update-infra-apply.yaml
    with:
      environment: ${{ matrix.customers }}
    secrets:
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS_DEVELOPMENT }}
